## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [1]:
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
# Group data by passenger class
grouped = titanic_df.groupby("Pclass")["Age"]

# Calculate the average age for each class
avg_age = grouped.mean()

# Count missing age values in each class
missing_age = grouped.apply(lambda x: x.isnull().sum())

# Create a summary DataFrame
result = pd.DataFrame({
    "avg_age": avg_age,
    "missing_age_count": missing_age
})

print(result)

          avg_age  missing_age_count
Pclass
1       38.233441                 30
2       29.877630                 11
3       25.140620                136

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [3]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
# fill missing "Embarked" with mode of each Pclass group
titanic_df["Embarked"] = titanic_df.groupby("Pclass")["Embarked"].transform(
    lambda x: x.fillna(x.mode()[0])
)

# print value counts (ascending) for each group
for pclass, group in titanic_df.groupby("Pclass"):
    print(f"Pclass {pclass}:")
    print(group["Embarked"].value_counts().sort_values(ascending=True))
    print()

Pclass 1:
Embarked
Q      2
C     85
S    129
Name: count, dtype: int64

Pclass 2:
Embarked
Q      3
C     17
S    164
Name: count, dtype: int64

Pclass 3:
Embarked
C     66
Q     72
S    353
Name: count, dtype: int64

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [188]:
# Group data by embark location and passenger class
grouped = titanic_df.groupby(["Embarked", "Pclass"])["Fare"]

# Calculate the average fare
avg_fare = grouped.mean().round(2)

# Convert the result into table format
result_df = avg_fare.unstack()

print(result_df)

Pclass         1      2      3
Embarked
C         104.72  25.36  11.21
Q          90.00  12.35  11.18
S          70.51  20.33  14.64

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [24]:
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
pd.set_option("display.max_columns", None)
fifa_df.head(2)

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,Total Attempts,On Target,Off Target,Target in Penalty,Target from Outside,Left Channel,Left Inside Channel,Central Channel,Right Inside Channel,Right Channel,Receptions MD,Receptions D,Attempted Line Breaks,Completed Line Breaks,Attempted Defensive Line Breaks,Completed Defensive Line Breaks,Yellow Cards,Red Cards,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,5,0,5,2,3,15,0,3,1,9,45,5,159,100,6,4,4,0,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,5,5,2,4,1,8,7,6,4,6,55,10,159,103,6,4,2,0,15,4,484,419,26,10,3,17,1,3

In [37]:
def z_normalization(group, cols_to_perform):
    for col in cols_to_perform:
        mean = group[col].mean()      # mean of the group
        std = group[col].std()        # std deviation of the group
        group[col + "_zscore"] = (group[col] - mean) / std   # new zscore column
    return group

In [191]:
grouped = fifa_df.groupby("Team")
# columns to normalize
cols_to_perform = ["Passes", "Passes Completed", "Attempted Line Breaks", "Completed Line Breaks"]

# group by team and apply the function
normalized_df = grouped.apply(lambda x: z_normalization(x, cols_to_perform))

# check new columns got added
normalized_df.head()

               Sl. No  Match No.       Against Group  Goal  Possession (%)  Inside Penalty Area  Outside Penalty Area  Assists  Total Attempts  On Target  Off Target  Target in Penalty  Target from Outside  Left Channel  Left Inside Channel  Central Channel  Right Inside Channel  Right Channel  Receptions MD  Receptions D  Attempted Line Breaks  Completed Line Breaks  Attempted Defensive Line Breaks  Completed Defensive Line Breaks  Yellow Cards  Red Cards  Fouls Against  Offsides  Passes  Passes Completed  Crosses  Crosses Completed  Corners  Free Kicks  Penalties Scored  Pts  Passes_zscore  Passes Completed_zscore  Attempted Line Breaks_zscore  Completed Line Breaks_zscore
Team
Argentina 8         9          5  Saudi Arabia     C     1              51                    1                     0        0              14          6           6                 10                    4            12                    4                5                     8             18             91            27                    195                    127                               10                                8             0          0              7        10     593               525       36                 15        9          21                 1    0      -0.208138                -0.157888                      0.364745                      0.087403
          46       47         24        Mexico     C     2              50                    1                     1        2               5          2           3                  2                    3            10                    6                2                     4             12             89             2                    150                    100                               10                                5             1          0             15         2     533               464       14                  2        4          23                 0    3      -0.630447                -0.574048                     -0.795806                     -0.945040
          77       78         39        Poland     C     2              67                    1                     1        2              25         13           8                 10                   15            25                    8                7                    10             26            150            36                    141                    126                               20                               16             1          0             11         0     862               814       22                  5        9           5                 0    3       1.685214                 1.813757                     -1.027917                      0.049164
          98       99         50     Australia     C     2              53                    2                     0        1              14          5           7                 11                    3            15                    6               11                     2             17            127             8                    181                    135                               16                                8             0          0              8         4     711               635        6                  1        1          15                 0    3       0.622403                 0.592566                      0.003684                      0.393311
          115     116         58   Netherlands     C     2              44                    2                     0        1              15          6           8                  5                   10             7                    7               13                     6             17            104             7                    203                    122                               24                                8             8          0             18         2     603               511       16                  4        8          30                 5    3      -0.137753                -0.253400                      0.571065                     -0.103791

In [192]:
# Calculate summary statistics for each team
result = grouped.agg({
    "Passes": ["min", "max"],
    "Yellow Cards": ["min", "max", "mean"],
    "Attempted Line Breaks": ["min", "max", "std"],
    "Possession (%)": "mean"
})

# Show all columns without wrapping
pd.set_option("display.expand_frame_repr", False)

print(result)

               Passes       Yellow Cards               Attempted Line Breaks                 Possession (%)
                  min   max          min max      mean                   min  max        std           mean
Team
Argentina         408   862            0   8  2.285714                   141  249  38.774685      49.285714
Australia         286   466            0   3  1.750000                   133  171  17.682383      31.250000
Belgium           512   685            1   3  1.666667                   167  195  14.422205      49.000000
Brazil            548   695            0   3  1.200000                   164  193  10.691118      50.400000
Cameroon          295   500            1   5  2.666667                   144  182  19.857828      38.333333
Canada            448   536            2   4  2.666667                   102  176  37.753587      44.333333
Costa Rica        231   454            1   3  2.000000                    86  154  38.974351      27.333333
Croatia           461   724            0   2  1.142857                    97  259  54.499891      47.428571
Denmark           537   650            1   2  1.666667                   173  241  34.000000      51.333333
Ecuador           429   484            0   2  1.000000                   143  177  17.009801      42.666667
England           508   810            0   1  0.200000                   133  208  29.676590      57.200000
France            358   734            0   3  1.142857                   126  179  21.407609      44.857143
Germany           352   827            0   3  1.000000                   143  256  56.624494      53.000000
Ghana             319   460            2   4  2.666667                   122  188  33.020196      37.000000
Iran              232   463            2   3  2.333333                    56  195  77.526340      31.666667
Japan             225   591            0   3  1.500000                   104  253  64.048810      30.250000
Korea Republic    359   548            1   2  1.500000                   139  201  27.072434      42.250000
Mexico            356   500            1   4  2.333333                   127  198  40.706265      46.666667
Morocco           229   583            0   3  1.285714                   128  157  10.641339      34.285714
Netherlands       403   786            0   4  1.800000                   168  198  12.759310      44.000000
Poland            303   466            1   3  1.750000                    79  156  36.326070      32.000000
Portugal          461   678            0   3  1.200000                   165  197  13.049904      53.800000
Qatar             424   457            0   4  2.333333                   159  174   7.767453      39.333333
Saudi Arabia      267   560            2   6  4.666667                   147  205  29.022979      36.666667
Senegal           277   511            1   3  1.750000                   143  184  16.938615      38.500000
Serbia            403   513            2   7  4.000000                   140  184  22.188586      42.666667
Spain             647  1070            0   1  0.500000                   186  237  24.289916      67.000000
Switzerland       403   512            1   4  2.250000                   157  178   9.032349      43.000000
Tunisia           328   501            1   3  1.666667                   153  200  24.419937      38.666667
United States     427   572            0   4  1.250000                   143  204  27.693260      47.000000
Uruguay           390   528            1   3  2.000000                   146  186  22.030282      41.000000
Wales             325   508            1   2  1.666667                   104  208  53.028294      41.000000

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

### `Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [109]:
df = pd.read_csv("ipl_deliveries.csv")
df.head()

        ID                            Team  innings  overs  ballnumber       batter          bowler  non-striker extra_type  batsman_run  extras_run  total_run  non_boundary  isWicketDelivery player_out kind fielders_involved       BattingTeam     BowlingTeam
0  1312200  Rajasthan RoyalsGujarat Titans        1      0           1  YBK Jaiswal  Mohammed Shami   JC Buttler        NaN            0           0          0             0                 0        NaN  NaN               NaN  Rajasthan Royals  Gujarat Titans
1  1312200  Rajasthan RoyalsGujarat Titans        1      0           2  YBK Jaiswal  Mohammed Shami   JC Buttler    legbyes            0           1          1             0                 0        NaN  NaN               NaN  Rajasthan Royals  Gujarat Titans
2  1312200  Rajasthan RoyalsGujarat Titans        1      0           3   JC Buttler  Mohammed Shami  YBK Jaiswal        NaN            1           0          1             0                 0        NaN  NaN               NaN  Rajasthan Royals  Gujarat Titans
3  1312200  Rajasthan RoyalsGujarat Titans        1      0           4  YBK Jaiswal  Mohammed Shami   JC Buttler        NaN            0           0          0             0                 0        NaN  NaN               NaN  Rajasthan Royals  Gujarat Titans
4  1312200  Rajasthan RoyalsGujarat Titans        1      0           5  YBK Jaiswal  Mohammed Shami   JC Buttler        NaN            0           0          0             0                 0        NaN  NaN               NaN  Rajasthan Royals  Gujarat Titans

In [110]:
df.head(2)

        ID                            Team  innings  overs  ballnumber       batter          bowler non-striker extra_type  batsman_run  extras_run  total_run  non_boundary  isWicketDelivery player_out kind fielders_involved       BattingTeam     BowlingTeam
0  1312200  Rajasthan RoyalsGujarat Titans        1      0           1  YBK Jaiswal  Mohammed Shami  JC Buttler        NaN            0           0          0             0                 0        NaN  NaN               NaN  Rajasthan Royals  Gujarat Titans
1  1312200  Rajasthan RoyalsGujarat Titans        1      0           2  YBK Jaiswal  Mohammed Shami  JC Buttler    legbyes            0           1          1             0                 0        NaN  NaN               NaN  Rajasthan Royals  Gujarat Titans

In [195]:
# Filter only chasing innings
chasing_df = df[df["innings"] == 2]

# Calculate total runs and balls faced for each batter
batsman_stats = chasing_df.groupby("batter").agg(
    total_runs=("batsman_run", "sum"),
    balls_faced=("ballnumber", "count")
)

# Find the highest run scorer
highest_score = batsman_stats["total_runs"].idxmax()

# Calculate strike rate
batsman_stats["strike_rate"] = (
    batsman_stats["total_runs"] / batsman_stats["balls_faced"]
) * 100

# Keep batters who have faced at least 100 balls
eligible = batsman_stats[batsman_stats["balls_faced"] >= 100]

# Find the batter with the highest strike rate
best_strike_rate = eligible["strike_rate"].idxmax()

print("Highest scorer while chasing:", highest_score)
print("Best strike rate (100+ balls) while chasing:", best_strike_rate)

Highest scorer while chasing: V Kohli
Best strike rate (100+ balls) while chasing: PJ Cummins

### `Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [147]:
df.head(2)

        ID                            Team  innings  overs  ballnumber       batter          bowler non-striker extra_type  batsman_run  extras_run  total_run  non_boundary  isWicketDelivery player_out kind fielders_involved       BattingTeam     BowlingTeam
0  1312200  Rajasthan RoyalsGujarat Titans        1      0           1  YBK Jaiswal  Mohammed Shami  JC Buttler        NaN            0           0          0             0                 0        NaN  NaN               NaN  Rajasthan Royals  Gujarat Titans
1  1312200  Rajasthan RoyalsGujarat Titans        1      0           2  YBK Jaiswal  Mohammed Shami  JC Buttler    legbyes            0           1          1             0                 0        NaN  NaN               NaN  Rajasthan Royals  Gujarat Titans

In [146]:
df.groupby(["batter","bowler"]).agg(
    dismissals=("isWicketDelivery", "sum"),   # count of dismissals
    runs=("total_run", "sum")                 # runs conceded
).sort_values(by=["dismissals", "runs"], ascending=[False, True]).head(1)

                     dismissals  runs
batter    bowler
RG Sharma SP Narine           8   140

### `Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [165]:
df.head(2)

        ID                            Team  innings  overs  ballnumber       batter          bowler non-striker extra_type  batsman_run  extras_run  total_run  non_boundary  isWicketDelivery player_out kind fielders_involved       BattingTeam     BowlingTeam                       pair
0  1312200  Rajasthan RoyalsGujarat Titans        1      0           1  YBK Jaiswal  Mohammed Shami  JC Buttler        NaN            0           0          0             0                 0        NaN  NaN               NaN  Rajasthan Royals  Gujarat Titans  (JC Buttler, YBK Jaiswal)
1  1312200  Rajasthan RoyalsGujarat Titans        1      0           2  YBK Jaiswal  Mohammed Shami  JC Buttler    legbyes            0           1          1             0                 0        NaN  NaN               NaN  Rajasthan Royals  Gujarat Titans  (JC Buttler, YBK Jaiswal)

In [207]:
# make a batting pair (order-independent)
df["pair"] = df.apply(lambda x: tuple(sorted([x["batter"], x["non-striker"]])), axis=1)

# total runs scored by each pair together
pair_runs = df.groupby("pair")["batsman_run"].sum().sort_values(ascending=False)

# pretty print top pair
top_pair, top_runs = pair_runs.index[0], pair_runs.iloc[0]
print(f"Successful Batting Pair: {top_pair[0]} & {top_pair[1]}")
print(f"Runs Scored Together: {top_runs}")

Successful Batting Pair: AB de Villiers & V Kohli
Runs Scored Together: 3040

### `Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [186]:
# pair (order-independent)
df["pair"] = df.apply(lambda x: tuple(sorted([x["batter"], x["non-striker"]])), axis=1)

# runs, balls faced (wides included as per note), dismissals for each pair
pair_stats = df.groupby("pair").agg(
    Runs=("batsman_run", "sum"),
    Balls=("ballnumber", "count"),
    Dismissals=("isWicketDelivery", "sum")
).reset_index()


# split pair tuple into two columns
pair_stats[["Batsman1", "Batsman2"]] = pd.DataFrame(pair_stats["pair"].tolist(), index=pair_stats.index)

# # average = runs per dismissal, strike rate = runs per 100 balls
pair_stats["Avg"] = (pair_stats["Runs"] / pair_stats["Dismissals"]).round(2)
pair_stats["StrikeRate"] = (pair_stats["Runs"] / pair_stats["Balls"] * 100).round(2)

# # final clean dataframe
final_df = pair_stats[["Batsman1", "Batsman2", "Runs", "Avg", "StrikeRate"]]

final_df.head()

         Batsman1         Batsman2  Runs   Avg  StrikeRate
0  A Ashish Reddy         A Mishra    38  38.0      122.58
1  A Ashish Reddy  AA Jhunjhunwala     4   4.0       80.00
2  A Ashish Reddy         CL White    12  12.0      133.33
3  A Ashish Reddy     DB Ravi Teja    10   inf      142.86
4  A Ashish Reddy        DJG Sammy    44  22.0      129.41